# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000
#
# test: &test
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000

development:
  adapter: postgresql
  host: 127.0.0.1
  encoding: unicode
  database: ndc_sandbox_dev
  pool: 5
  username: rubypostgres
  password: password1

test: &test
  adapter: postgresql
  encoding: unicode
  database: ndc_sandbox_test
  pool: 5
  username: rubypostgres
  password: password1
